version: '3'

services:
  agent:
    container_name: newrelic-ruby-kata
    build:
      context: .
      dockerfile: Dockerfile
    cap_add:
      - SYS_PTRACE
    network_mode: host
    pid: host
    privileged: true
    volumes:
      - "/:/host:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - type: bind
        source: /home/ubuntu/logs
        target: /home/newrelic-ruby-kata/log
    restart: unless-stopped